In [1]:
import numpy as np


## one D array

In [3]:
a=[1,2,3]
b=np.array(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3]


## Two D Array

In [6]:
c=[[1,2,3],[4,5,6],[7,8,9]]
d=np.array(c)
print(type(d))
print(d)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(d+2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
d.astype('int')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Create Numpy Array (arange,zeros,ones,full,eye,rand,randn.randint,linspace)

In [15]:
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [17]:
f=np.arange(0,7,2)
f

array([0, 2, 4, 6])

In [35]:
g=np.zeros((4,4))
g

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
h=np.ones((3,3))
h

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
i=np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
j=np.full([2,3],1)
j

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
k=np.linspace(1,10,3)
k

array([ 1. ,  5.5, 10. ])

In [51]:
import random
np.random.rand(3,4)

array([[0.85312497, 0.6093182 , 0.94295695, 0.47140172],
       [0.77298334, 0.21397839, 0.19163442, 0.23918716],
       [0.7168368 , 0.65099205, 0.61463943, 0.89430512]])

In [54]:
# includes negative values
np.random.randn(3,4)

array([[ 0.8688749 , -0.10133287,  0.21156552, -0.05514304],
       [ 0.60847762, -0.72458601, -1.07585046,  1.1931455 ],
       [ 0.74707367, -0.08329668, -1.8144259 ,  1.16047965]])

In [63]:
# only int values
a=np.random.randint(3,10)
b=np.random.randint(1,50,5)
print(a)
print(b)

7
[ 9 41 48  7 20]


## Array Methods  (reshape,min,max,argmax,argmin,shape,size,dtype,astype)

In [60]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
ar=np.random.randint(1,25,10)
ar

array([13, 11, 23,  1,  5, 16, 16, 16, 12,  5])

In [83]:
b=arr.reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
# to find the min, max and their index
print(ar.max())
print(ar.min())
print(ar.argmax())
print(ar.argmin())

23
1
2
3


In [85]:
# Dimension
b.shape

(5, 5)

In [89]:
# No of elements
b.size

25

In [94]:
# type of datatype
ar.dtype

dtype('int32')

In [98]:
# convert the datatype
b.astype(float)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

## Indexing and Selection

In [100]:
arr=np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
# selection or slice
arr[1:5]

array([1, 2, 3, 4])

In [104]:
# Index
arr[4]

4

In [107]:
# Broadcasting - Setting values with indexx range
arr[4:7]=99
arr

array([ 0,  1,  2,  3, 99, 99, 99,  7,  8])

In [110]:
arr=np.array([[1,2,3],[7,8,9],[4,5,6,]])
arr

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [112]:
arr[1]

array([7, 8, 9])

In [114]:
arr[1][2]

9

In [126]:
arr[:3,:2]

array([[1, 2],
       [7, 8],
       [4, 5]])

In [129]:
arr[arr>5]

array([7, 8, 9, 6])

In [142]:
# Fancy Indexing
arr=np.zeros([10,10])
arr_length=arr.shape[0]
arr_length

10

In [144]:
for i in range(arr_length):
    arr[i]=i
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [147]:
# selection
arr[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [149]:
arr[[6,2,1,4]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [152]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
bool_arr=arr>4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [160]:
bool_arr.dtype

dtype('bool')

## Arithmetic opeartion

In [165]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
arr_2=arr+arr
arr_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [170]:
arr_3=arr_2*arr
arr_3

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162, 200])

In [172]:
new=arr_3-arr
new

array([  0,   1,   6,  15,  28,  45,  66,  91, 120, 153, 190])

## Stacking  (Horizontal, vertical, column,concatenate)

In [178]:
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
print('a'        , a)
print('b'        , b)

a [[1 2]
 [3 4]]
b [[5 6]
 [7 8]]


In [181]:
# Vertical stack
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [183]:
# Horizontal Stack
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [187]:
# Column Stack
np.column_stack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [189]:
# Column Stack
c=[7,8]
np.column_stack([a,c])

array([[1, 2, 7],
       [3, 4, 8]])

In [197]:
# Concatenate (0==row wise)and (1==column wise)
print("first ",np.concatenate([a,b],0))
print("Second ",np.concatenate([a,b],1))
      

first  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Second  [[1 2 5 6]
 [3 4 7 8]]


## Splitting ( Horizontal, Vertical)

In [203]:
arr=[[7,8,9,10],[1,2,3,4],[4,5,6,7],[2,5,7,9]]
a=np.array(arr)
a

array([[ 7,  8,  9, 10],
       [ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 2,  5,  7,  9]])

In [205]:
# For splitting rows must be equally divideable. here 2 is no of horizontal parts or no of splitted arrays
np.vsplit(a,2)

[array([[ 7,  8,  9, 10],
        [ 1,  2,  3,  4]]), array([[4, 5, 6, 7],
        [2, 5, 7, 9]])]

In [209]:
# For splitting columns must be equally divideable. here 2 is no of horizontal parts or no of splitted arrays
np.hsplit(a,2)

[array([[7, 8],
        [1, 2],
        [4, 5],
        [2, 5]]), array([[ 9, 10],
        [ 3,  4],
        [ 6,  7],
        [ 7,  9]])]

## Linear Algebra (Rank, Determinant, trace, inverse, power, Solve Linear Algebra)

In [244]:
a = np.array([[6, 1, 1], 
              [4, -2, 5], 
              [2, 8, 7]]) 
a

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [249]:
# Rank (The rank is how many of the rows are "unique": not made of other rows.) (Same for columns.)
print("rank " ,np.linalg.matrix_rank(a))
print("trace ",np.trace(a))
print("determinant ", np.linalg.det(a))
print("inverse " ,np.linalg.inv(a))
print("power ", np.linalg.matrix_power(a, 2))

rank  3
trace  11
determinant  -306.0
inverse  [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
power  [[42 12 18]
 [26 48 29]
 [58 42 91]]


In [257]:
a=np.ones([3,3])
b=a.astype(int)
print(b)
print(np.linalg.matrix_rank(b))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
1


In [258]:
# Trace  (the sum of elements on the main diagonal (from the upper left to the lower right) of A)
np.trace(b)

3

In [259]:
# Determinant
np.linalg.det(b)

0.0

In [264]:
# Solve Linear Algebra
# x + 2*y = 8
# 3*x + 4*y = 18
# coefficients 
a = np.array([[1, 2], [3, 4]]) 
# constants 
b = np.array([8, 18]) 
print(a)
print(b)

[[1 2]
 [3 4]]
[ 8 18]


In [266]:
print("Solution of linear equations:", np.linalg.solve(a, b))

Solution of linear equations: [2. 3.]


### Reverse, Tile, Repeat, Unique

In [270]:
arr=np.array([[12,12,12],[12,4,5],[6,7,8]])
arr

array([[12, 12, 12],
       [12,  4,  5],
       [ 6,  7,  8]])

In [272]:
# Reverse only row positions row 1 with row 3
arr[::-1]

array([[ 6,  7,  8],
       [12,  4,  5],
       [12, 12, 12]])

In [274]:
# Reverse both row and column with 1 & 3.
arr[::-1,::-1]

array([[ 8,  7,  6],
       [ 5,  4, 12],
       [12, 12, 12]])

In [294]:
# Repeat & Tile
# Repeat --> repeats each elements as per the number given. first one elements ends then next element starts.
# Tile --> repeats the whole list first and then next will be as per the number given.
a=[1,2,3]
print(np.repeat(a,3))
print(np.tile(a,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [298]:
# Unique & Counts
# The asarray() function is used to convert an given input to an array.
# Input data, in any form that can be converted to an array.
# This includes lists, lists of tuples, tuples, tuples of tuples, tuples of lists and ndarrays.
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))


[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
